### ISSUE TITLE
Undefined symbols for architecture armv7:   "_OBJC_CLASS_$_RSKImageCropViewController", referenced from: objc-class-ref in DetailsViewController.o

### ISSUE THREAD

**Issue by sumitmagdum** [ruslanskorb/RSKImageCropper#122] opened 2016-11-30 11:50 UTC

**Comment by ruslanskorb** [comment] 2016-11-30 15:19
@sumitmagdum Can you provide more information about your problem?

**Comment by ruslanskorb** [comment] 2016-12-01 05:40
I guess that the problem in your project settings - http://stackoverflow.com/a/6429568/2134682.

Will close the issue for now. If the problem is not related to your project configuration feel free to reopen it.

**Closed by ruslanskorb** 2016-12-01 05:40 UTC
Labels: user bug
