### ISSUE TITLE
cropImage layout was wrong when use RSKImageCropModeCustom

### ISSUE THREAD

**Issue by yangqingren** [ruslanskorb/RSKImageCropper#212] opened 2019-07-22 10:42 UTC
hello, cropImage wrong when use RSKImageCropModeCustom
Reproduction steps:
1. Set the example to cropMode:RSKImageCropModeCustom；
2. Use CGSize aspectRatio = CGSizeMake (16.0f, 9.0f);
3. Rotate 90° and move the picture downward.
Discovery: The picture flashed and the layout was wrong.

**Comment by ruslanskorb** [comment] 2019-07-22 12:07
Hi @yangqingren,

I can't reproduce your issue. Could you provide a test project?

Thanks!

**Comment by yangqingren** [comment] 2019-07-22 12:31
Using your example, CGSizeMake (16.0f, 9.0f) (not square),
Rotate and drag down to the bottom;
Should be reproducible.(If it weren't for the problems I caused)


I will solve this problem temporarily  by :

-(CGRect)cropRect
{
    CGRect maskRect = self.maskRect;
    CGFloat rotationAngle = self.rotationAngle;
    CGRect rotatedImageScrollViewFrame = self.imageScrollView.frame;
    float zoomScale = 1.0 / self.imageScrollView.zoomScale;
    
    UIScrollView *scrollView = [[UIScrollView alloc] init];
    scrollView.frame = self.imageScrollView.frame;
    scrollView.contentSize = self.imageScrollView.contentSize;
    scrollView.contentOffset = self.imageScrollView.contentOffset;
    scrollView.transform = CGAffineTransformIdentity;
    
    CGRect imageScrollViewFrame = scrollView.frame;
    scrollView.frame = self.maskRect;
    ...
    ...
    ...
    // self.imageScrollView.transform = imageScrollViewTransform;
    // self.imageScrollView.frame = imageScrollViewFrame;


with a new object to calculate ‘ cropRect’

**Comment by ruslanskorb** [comment] 2019-07-22 12:51
@yangqingren How do you rotate an image? Programmatically or with a gesture?

**Comment by yangqingren** [comment] 2019-07-22 12:52
with a gesture

**Comment by ruslanskorb** [comment] 2019-07-22 13:02
@yangqingren Could you record a video of what exactly is wrong?

**Comment by yangqingren** [comment] 2019-07-22 13:08
have been sent ‘ruslan@rsk-lab.com ’

**Comment by ruslanskorb** [comment] 2019-07-22 14:46
@yangqingren Thank! Now I noticed the problem.

**Comment by ruslanskorb** [comment] 2019-07-22 14:47
[RPReplay_Final1563800730.MP4.zip](https://github.com/ruslanskorb/RSKImageCropper/files/3417957/RPReplay_Final1563800730.MP4.zip)

**Comment by ruslanskorb** [comment] 2019-07-23 12:21
Hi @yangqingren,

I pushed the fix in **develop** branch. Could you test it?

**Comment by yangqingren** [comment] 2019-07-23 12:46
The same problem has arisen by the branch #213
You can test this way：
`- (void)onAddPhotoButtonTouch:(UIButton *)sender
{
    UIImage *photo = [UIImage imageNamed:@"photo"];
    RSKImageCropViewController *imageCropVC = [[RSKImageCropViewController alloc] initWithImage:photo cropMode:RSKImageCropModeCustom];
    imageCropVC.dataSource = self;
    imageCropVC.delegate = self;
    imageCropVC.rotationEnabled = YES;
    [self.navigationController pushViewController:imageCropVC animated:YES];
}

// Returns a custom rect for the mask.
- (CGRect)imageCropViewControllerCustomMaskRect:(RSKImageCropViewController *)controller
{
    CGSize aspectRatio = CGSizeMake(16.0f, 9.0f);
    
    CGFloat viewWidth = CGRectGetWidth(controller.view.frame);
    CGFloat viewHeight = CGRectGetHeight(controller.view.frame);
    
    CGFloat maskWidth;
    if ([controller isPortraitInterfaceOrientation]) {
        maskWidth = viewWidth;
    } else {
        maskWidth = viewHeight;
    }
    
    CGFloat maskHeight;
    do {
        maskHeight = maskWidth * aspectRatio.height / aspectRatio.width;
        maskWidth -= 1.0f;
    } while (maskHeight != floor(maskHeight));
    maskWidth += 1.0f;
    
    CGSize maskSize = CGSizeMake(maskWidth, maskHeight);
    
    CGRect maskRect = CGRectMake((viewWidth - maskSize.width) * 0.5f,
                                 (viewHeight - maskSize.height) * 0.5f,
                                 maskSize.width,
                                 maskSize.height);
    
    return maskRect;
}

// Returns a custom path for the mask.
- (UIBezierPath *)imageCropViewControllerCustomMaskPath:(RSKImageCropViewController *)controller
{
    CGRect rect = controller.maskRect;
    CGPoint point1 = CGPointMake(CGRectGetMinX(rect), CGRectGetMaxY(rect));
    CGPoint point2 = CGPointMake(CGRectGetMaxX(rect), CGRectGetMaxY(rect));
    CGPoint point3 = CGPointMake(CGRectGetMaxX(rect), CGRectGetMinY(rect));
    CGPoint point4 = CGPointMake(CGRectGetMinX(rect), CGRectGetMinY(rect));
    
    UIBezierPath *rectangle = [UIBezierPath bezierPath];
    [rectangle moveToPoint:point1];
    [rectangle addLineToPoint:point2];
    [rectangle addLineToPoint:point3];
    [rectangle addLineToPoint:point4];
    [rectangle closePath];
    
    return rectangle;
}

// Returns a custom rect in which the image can be moved.
- (CGRect)imageCropViewControllerCustomMovementRect:(RSKImageCropViewController *)controller
{
    if (controller.rotationAngle == 0) {
        return controller.maskRect;
    } else {
        CGRect maskRect = controller.maskRect;
        CGFloat rotationAngle = controller.rotationAngle;
        
        CGRect movementRect = CGRectZero;
        
        movementRect.size.width = CGRectGetWidth(maskRect) * fabs(cos(rotationAngle)) + CGRectGetHeight(maskRect) * fabs(sin(rotationAngle));
        movementRect.size.height = CGRectGetHeight(maskRect) * fabs(cos(rotationAngle)) + CGRectGetWidth(maskRect) * fabs(sin(rotationAngle));
        
        movementRect.origin.x = CGRectGetMinX(maskRect) + (CGRectGetWidth(maskRect) - CGRectGetWidth(movementRect)) * 0.5f;
        movementRect.origin.y = CGRectGetMinY(maskRect) + (CGRectGetHeight(maskRect) - CGRectGetHeight(movementRect)) * 0.5f;
        
        movementRect.origin.x = floor(CGRectGetMinX(movementRect));
        movementRect.origin.y = floor(CGRectGetMinY(movementRect));
        movementRect = CGRectIntegral(movementRect);
        
        return movementRect;
    }
}
`

**Comment by ruslanskorb** [comment] 2019-07-23 12:50
@yangqingren Did you test [develop](https://github.com/ruslanskorb/RSKImageCropper/tree/develop) branch?

**Comment by ruslanskorb** [comment] 2019-07-23 12:54
This is what I see - [RPReplay_Final1563886346.MP4.zip](https://github.com/ruslanskorb/RSKImageCropper/files/3422113/RPReplay_Final1563886346.MP4.zip)

**Comment by ruslanskorb** [comment] 2019-07-24 11:03
Hi @yangqingren! Could you check the latest changes in the **develop** branch?

**Comment by yangqingren** [comment] 2019-07-24 11:35
nice, this problem has been solved in the dev.

**Comment by ruslanskorb** [comment] 2019-07-24 11:37
@yangqingren Glad to hear it!

**Closed** 2019-07-25 07:18 UTC
Labels: bug

**Comment by ruslanskorb** [comment] 2019-07-25 07:27
@yangqingren Fixed in [2.2.3](https://github.com/ruslanskorb/RSKImageCropper/releases/tag/2.2.3) 🚀  Thank you for reporting!
