### ISSUE TITLE
Support iCloud pictures ?

### ISSUE THREAD

**Issue by magrinj** [ruslanskorb/RSKImageCropper#117] opened 2016-09-20 14:34 UTC
Hello, is this library supporting picture coming from iCloud ? I use this library from `react-native-image-crop-picker` and the iCloud pictures show a black screen during the crop

**Comment by ruslanskorb** [comment] 2016-09-20 16:05
Hi @magrinj,

Personally, I have not used `RSKImageCropper` in conjunction with iCloud. However, in theory, it should work without any problems.

Can you log the image to the console and share result with us?

**Comment by magrinj** [comment] 2016-09-22 07:43
Hi @ruslanskorb,

thanks for your answer!

The current logs are: 

```
2016-09-22 09:42:01.273133 BeJoe[8461:1731311] [Generic] Creating an image format with an unknown type is an error
2016-09-22 09:42:04.172763 BeJoe[8461:1732283] [Generic] Failed to load image data for asset <private> with format 9999
```

I'm going to log picture in the library

**Comment by magrinj** [comment] 2016-09-22 07:51
The picture is nil, so I think the problem didn't come from your library but from the one that select the picture: https://github.com/questbeat/QBImagePicker

<img width="309" alt="screen shot 2016-09-22 at 9 49 17 am" src="https://cloud.githubusercontent.com/assets/3551795/18740418/daf5857e-80a9-11e6-9877-c18236b84971.png">

I'm going to look in this other library to try to solve this issue

**Comment by ruslanskorb** [comment] 2016-09-22 11:07
Looks like `QBImagePicker` can't load an image from the source.

As the problem is not related to `RSKImageCropper` I have decided to close the issue.

Good luck in solving your problem!

**Closed by ruslanskorb** 2016-09-22 11:07 UTC
Labels: question
