### ISSUE TITLE
Using .Circle but getting non-circular result in didCropImage

### ISSUE THREAD

**Issue by edenman** [ruslanskorb/RSKImageCropper#151] opened 2017-04-18 19:01 UTC
Here's how I'm creating my crop controller:
```swift
let imageCropViewController = RSKImageCropViewController(image: image)
imageCropViewController.delegate = self
imageCropViewController.cropMode = .Circle
imageCropViewController.avoidEmptySpaceAroundImage = true
```
It doesn't happen often, but occasionally I'll see a crash where the `croppedImage` passed into `didCropImage` has width != height.  I added some additional logging to try and figure out what's happening: the latest occurence, the original image had the same dimensions as the croppedImage (w=823.0, h=960.0).

Is there any reason this would happen?  It doesn't seem to be related to phone/os version.

**Comment by ruslanskorb** [comment] 2017-04-19 06:00
@edenman Did you catch this crash manually while debugging? Actually, I see no reason why it can happen. It would be nice if you could provide any additional information or a sample project with this problem.

**Comment by edenman** [comment] 2017-04-19 16:51
Nope, this was a crash in the wild, uploaded to Sentry (our crash reporting tool).  I've never been able to repro it :/

**Comment by ruslanskorb** [comment] 2017-04-19 19:06
@edenman Can you share one of the crash reports? Or part of it?

**Comment by edenman** [comment] 2017-04-19 22:15
Sorry, "crash" isn't the right word.  It's a non-fatal exception that I log to Sentry.  Here's the stack:

```
  recharge-consumer-ios0x1001d9368  LogNonFatal(String) -> () (AppDelegate.swift:223)
  recharge-consumer-ios0x100265058  specialized ChangeProfilePictureView.imageCropViewController(RSKImageCropViewController, didCropImage : UIImage, usingCropRect : CGRect, rotationAngle : CGFloat) -> () (ChangeProfilePictureView.swift:133)
  recharge-consumer-ios0x100263fdc  @objc ChangeProfilePictureView.imageCropViewController(RSKImageCropViewController, didCropImage : UIImage, usingCropRect : CGRect, rotationAngle : CGFloat) -> () (ChangeProfilePictureView.swift:0)
  RSKImageCropper     0x100fa3c1c  __39-[RSKImageCropViewController cropImage]_block_invoke_2 (RSKImageCropViewController.m:959)
  libdispatch         0x1831494bc  _dispatch_call_block_and_release
  libdispatch         0x18314947c  _dispatch_client_callout
  libdispatch         0x18314eb84  __dispatch_main_queue_callback_4CF
  CoreFoundation      0x1836b4d50  ___CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
  CoreFoundation      0x1836b2bb8  ___CFRunLoopRun
  CoreFoundation      0x1835dcc50  CFRunLoopRunSpecific
  GraphicsServices    0x184ec4088  _GSEventRunModal
  UIKit               0x1888c6088  _UIApplicationMain
  recharge-consumer-ios0x1001d9fb0  main (AppDelegate.swift:44)
  libdyld             0x18317a8b8  _start
```
And the message:
```
Image isn't square (w=823.0, h=960.0) from original (w=823.0, h=960.0)
```

It's happened to three users:
iPhone7,1 on iOS 10.2
iPhone7,2 on iOS 10.2.1
iPhone5S on iOS 9.3.2

**Comment by ruslanskorb** [comment] 2017-04-20 05:58
@edenman Thanks. One more thing. Can you share your method `imageCropViewController(_:didCropImage:usingCropRect:rotationAngle:)` implemented in `ChangeProfilePictureView`?

**Comment by edenman** [comment] 2017-04-20 17:29
```
	func imageCropViewController(controller: RSKImageCropViewController, didCropImage croppedImage: UIImage, usingCropRect cropRect: CGRect, rotationAngle: CGFloat) {
		guard let delegate = delegate else {
			LogNonFatal("No delegate")
			return
		}

		guard croppedImage.size.width == croppedImage.size.height else {
			let original = controller.originalImage
			LogNonFatal("Image isn't square (w=\(croppedImage.size.width), h=\(croppedImage.size.height)) from original (w=\(original.size.width), h=\(original.size.height))")
			ErrorActions.setErrorDisplayText(ErrorActions.genericContactSupportError)
			return
		}
		// Handle the image here		
		delegate.shouldDismissViewControllerAnimated(true, completion: nil)
	}
```

**Comment by ruslanskorb** [comment] 2017-04-20 18:42
@edenman Do you have any swizzling code in your project?

**Comment by edenman** [comment] 2017-04-20 20:02
@ruslanskorb nope

**Comment by ruslanskorb** [comment] 2017-04-20 20:05
@edenman Can you include `cropRect` in your log message?

**Comment by edenman** [comment] 2017-04-20 20:13
@ruslanskorb willdo.  it'll probably be a couple weeks until I do another release, though.  I just finally updated to swift3 and I wanna make sure I get sufficient usage internally before release.  I'll update this thread next time it happens.  Thanks again!

**Comment by ruslanskorb** [comment] 2017-04-20 20:19
@edenman Thanks! I will wait for any information from you.
p.s. Is your app available in the App Store?

**Comment by edenman** [comment] 2017-04-20 21:00
@ruslanskorb yup: https://itunes.apple.com/us/app/recharge-luxury-hotels-unlocked/id999743644?mt=8

**Comment by ruslanskorb** [comment] 2017-05-12 16:11
@edenman Is there any news?

**Comment by edenman** [comment] 2017-05-12 16:23
@ruslanskorb sorry, no.  I released the new version a week ago but nobody has hit the issue since then.  Will update if/when they do!

**Comment by ruslanskorb** [comment] 2017-05-12 16:37
@edenman OK. Thanks!

I will close the issue for now. If/when anyone face this problem again and you will have more information feel free to reopen it.

**Comment by edenman** [comment] 2017-05-14 20:43
@ruslanskorb looks like i don't have "reopen" permission here, but the issue just happened in the wild again, so i have the extra info you requested:

```
Image isn't square (w=1694.0, h=2234.0) from original (w=1694.0, h=2510.0) with cropRect (-345.0, -43.0, 2277.0, 2277.0)
```

**Comment by ruslanskorb** [comment] 2017-05-20 11:33
Hi @edenman,

Sorry for the delayed response.
What is the parent view controller of `imageCropViewController`?

**Comment by edenman** [comment] 2017-05-22 17:40
In the original code snippet, `self` is `ChangeProfilePictureView`, a custom subclass of `UIView`.
In [this snippet](https://github.com/ruslanskorb/RSKImageCropper/issues/151#issuecomment-295825512), `delegate` is `SettingsViewController` which is a `UIViewController`.

**Comment by ruslanskorb** [comment] 2017-05-22 17:47
@edenman Is `SettingsViewController` embedded in another view controller?

**Comment by edenman** [comment] 2017-05-22 18:58
@ruslanskorb yup.  The two hierarchies that contain a `ChangeProfilePictureView`:

  `RootViewController` -> `SignedOutContainerViewController` -> `SignUpSectionViewController` -> `SignUpViewController`.

  `RootViewController` -> `SignedInContainerViewController` -> `SettingsSectionViewController` -> `SettingsViewController`.

**Comment by edenman** [comment] 2017-06-29 18:40
@ruslanskorb any more thoughts on this? It still happens periodically and I still can't figure out how to repro.

**Comment by ruslanskorb** [comment] 2017-06-30 13:58
@edenman It's hard to say without reproducing the problem. My only guess is that the reason for this may be a layout. I would ask you to collect any additional data, such as phone orientation, constraints, and all the others that may seem important to you.

**Comment by ruslanskorb** [comment] 2017-07-02 08:51
@edenman Also I'd like to ask you to try a new [1.6.3](https://github.com/ruslanskorb/RSKImageCropper/releases/tag/1.6.3) version and let me know if something changes.

**Comment by ruslanskorb** [comment] 2017-07-28 16:25
@edenman Is there any news?

**Comment by edenman** [comment] 2017-07-28 17:02
Nope.  I released a new version of my app on 7/13 (with RSK 1.6.3) and the issue hasn't happened again since then.  Feel free to close this if you want.

**Comment by ruslanskorb** [comment] 2017-07-28 18:10
Thanks for the info! :thumbsup: Let's wait a little longer and close the task if the problem does not arise again.

**Comment by ruslanskorb** [comment] 2017-08-11 09:28
@edenman Has anything changed?

**Comment by edenman** [comment] 2017-08-11 16:45
Nope

**Comment by ruslanskorb** [comment] 2017-08-16 14:37
@edenman Okay, then let's close the issue. Thank you for all the information you provided!

**Closed by ruslanskorb** 2017-08-16 14:37 UTC
Labels: needs more information
