### ISSUE TITLE
Thin white border added to cropped image

### ISSUE THREAD

**Issue by brod-ie** [ruslanskorb/RSKImageCropper#114] opened 2016-08-30 16:47 UTC
I've noticed the cropper is adding a thin white border around the edges of masked photos, here's my code:

    // MARK: Cropper Data Source
    
    func imageCropViewControllerCustomMaskRect(controller: RSKImageCropViewController) -> CGRect {
        let maskSize = CGSizeMake(225, 400)
        let viewWidth: CGFloat = CGRectGetWidth(controller.view.frame)
        let viewHeight: CGFloat = CGRectGetHeight(controller.view.frame)
        let maskRect: CGRect = CGRectMake((viewWidth - maskSize.width) * 0.5, (viewHeight - maskSize.height) * 0.5, maskSize.width, maskSize.height)
        return maskRect
    }
    
    func imageCropViewControllerCustomMaskPath(controller: RSKImageCropViewController) -> UIBezierPath {
        return UIBezierPath(rect: controller.maskRect)
    }

    func imageCropViewControllerCustomMovementRect(controller: RSKImageCropViewController) -> CGRect {
        return controller.maskRect
    }

[And an example result](https://cloud.githubusercontent.com/assets/1520630/18098309/982486aa-6ed9-11e6-8592-a302d03f06d5.jpeg)

What am I doing wrong?

**Comment by ruslanskorb** [comment] 2016-08-30 17:35
@brod-ie Can you show your configuration of `RSKImageCropViewController` instance?

**Comment by brod-ie** [comment] 2016-08-30 19:27
It's:
```
            let imageCropVC: RSKImageCropViewController = RSKImageCropViewController(image: image)
            imageCropVC.delegate = self
            imageCropVC.dataSource = self
            imageCropVC.avoidEmptySpaceAroundImage = true
            imageCropVC.applyMaskToCroppedImage = true
            imageCropVC.cropMode = RSKImageCropMode.Custom
            imageCropVC.rotationEnabled = false
```

**Comment by ruslanskorb** [comment] 2016-08-31 05:14
Everything about `RSKImageCropViewController` looks good to me.

I created a [test project](https://dl.dropboxusercontent.com/u/89891480/brod-ie.zip) with your code, but did not see the problem you described.

Please look at it. Maybe it will help to resolve your problem.

p.s. Also I can suggest to check the frame of the image view with the cropped image.

**Comment by brod-ie** [comment] 2016-08-31 12:27
Thanks for your help.

Setting `imageCropVC.applyMaskToCroppedImage` to false seems to of fixed the issue?

**Comment by ruslanskorb** [comment] 2016-08-31 12:30
It should work even when `applyMaskToCroppedImage` is set to `true`.

**Comment by ruslanskorb** [comment] 2016-09-01 05:38
@brod-ie Can you try to crop your image in the test project I provided above? Maybe the problem is  in it.

**Comment by ruslanskorb** [comment] 2016-09-05 07:07
@brod-ie Any news on this?

**Comment by brod-ie** [comment] 2016-09-05 09:11
I haven't investigated any further beyond confirming disabling 'applyMaskToCroppedImage' fixed the issue (on annual leave, will pick it up when I'm back in the office)

**Comment by ruslanskorb** [comment] 2016-09-22 11:15
@brod-ie I will close the issue for now. If the problem still persists and you have any additional information feel free to reopen it.

**Closed by ruslanskorb** 2016-09-22 11:15 UTC
Labels: needs more information
